import Link from "next/link";
import { ArrowLeft, BriefcaseBusiness, CheckCircle2, Download, MapPin, ShieldCheck, Smartphone, WalletCards } from "lucide-react";

const features = [
  ["برای متقاضیان", "خدمت مورد نیازت را ثبت کن، متخصص نزدیک را پیدا کن و روند کار و پرداخت را یکجا مدیریت کن.", MapPin],
  ["برای متخصصان", "درخواست‌های نزدیک را ببین، محدوده فعالیتت را تنظیم کن و فرصت‌های مناسب را سریع بپذیر.", BriefcaseBusiness],
  ["امن و شفاف", "احراز هویت، کیف پول، پرداخت امن و امتیازدهی، اعتماد دو طرف را در تمام مسیر حفظ می‌کند.", ShieldCheck],
];

export default function LandingPage() {
  return <main dir="rtl" className="min-h-screen overflow-hidden bg-slate-950 text-white">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><Link href="/" className="flex items-center gap-3 text-xl font-black"><span className="rounded-2xl bg-indigo-600 p-3"><BriefcaseBusiness /></span>کاروین</Link><Link href="/login" className="text-sm text-slate-300 hover:text-white">ورود به حساب</Link></nav>
    <section className="mx-auto grid max-w-7xl items-center gap-12 px-6 py-20 lg:grid-cols-2"><div><span className="rounded-full border border-indigo-400/30 bg-indigo-400/10 px-4 py-2 text-sm text-indigo-300">پلتفرم هوشمند خدمات محلی</span><h1 className="mt-7 text-5xl font-black leading-tight md:text-7xl">خدمت خوب،<span className="block text-indigo-400">همین نزدیکی است.</span></h1><p className="mt-6 max-w-xl text-lg leading-9 text-slate-400">کاروین، مسیر ارتباط متقاضیان خدمت و متخصصان قابل اعتماد را ساده، سریع و شفاف می‌کند.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="/app-release.apk" download className="flex items-center justify-center gap-2 rounded-2xl bg-indigo-600 px-6 py-4 font-bold hover:bg-indigo-500"><Download size={20} />دانلود مستقیم APK</a><Link href="/worker" className="flex items-center justify-center gap-2 rounded-2xl border border-slate-700 px-6 py-4 font-bold hover:bg-slate-900">ورود به پنل متخصصان <ArrowLeft size={18} /></Link></div></div><div className="relative rounded-[2rem] border border-indigo-500/20 bg-gradient-to-br from-indigo-950 to-slate-900 p-8 shadow-2xl shadow-indigo-950"><div className="absolute -left-8 -top-8 rounded-2xl bg-emerald-500 p-4 shadow-xl"><CheckCircle2 /></div><Smartphone className="mx-auto h-52 w-52 text-indigo-400" /><div className="mt-8 rounded-2xl bg-slate-950/80 p-5"><div className="flex items-center gap-3"><WalletCards className="text-emerald-400" /><div><p className="font-bold">همه‌چیز در یک اپلیکیشن</p><p className="text-sm text-slate-400">درخواست، ارتباط، پرداخت و امتیازدهی</p></div></div></div></div></section>
    <section className="mx-auto grid max-w-7xl gap-5 px-6 py-16 md:grid-cols-3">{features.map(([title, text, Icon]) => { const FeatureIcon = Icon as typeof MapPin; return <article key={title as string} className="rounded-3xl border border-slate-800 bg-slate-900/60 p-7"><FeatureIcon className="mb-5 text-indigo-400" size={32} /><h2 className="text-xl font-black">{title as string}</h2><p className="mt-3 leading-8 text-slate-400">{text as string}</p></article>; })}</section>
    <section className="mx-auto max-w-4xl px-6 py-16 text-center"><h2 className="text-3xl font-black">کاروین را همین امروز شروع کن</h2><p className="mt-4 text-slate-400">نسخه موبایل برای تجربه سریع‌تر در دسترس است.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><a href="/app-release.apk" className="rounded-xl border border-slate-700 px-5 py-3 text-sm">Google Play</a><a href="/app-release.apk" className="rounded-xl border border-slate-700 px-5 py-3 text-sm">App Store</a></div></section>
    <footer className="border-t border-slate-800 py-8 text-center text-sm text-slate-500">© ۱۴۰۵ کاروین — پلتفرم خدمات قابل اعتماد</footer>
  </main>;
}
